from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .inspection_result import RuntimeInspection


def is_runtime_ready(inspection: "RuntimeInspection") -> bool:
    return (
        inspection.lock_count == 10
        and inspection.door_count == 5
        and inspection.doors_with_required_key == 5
        and inspection.doors_with_creak_sound == 5
        and inspection.doors_with_locked_sound == 5
        and inspection.audio_volume_count == 5
        and inspection.audio_volumes_with_ambience == 5
        and inspection.unique_room_ambience_count == 5
        and inspection.audio_volumes_with_runtime_settings == 5
        and inspection.audio_volumes_with_footstep_surface == 5
        and inspection.unique_room_footstep_surface_count == 5
        and inspection.locks_with_expected_input == 10
        and inspection.locks_with_hint == 10
        and inspection.locks_with_input_sound == 10
        and inspection.unique_lock_input_sound_count >= 7
        and inspection.unique_lock_success_sound_count >= 5
        and inspection.locks_with_detail_components == 10
        and inspection.locks_with_kind_hardware == 10
        and inspection.unique_runtime_lock_kind_count == 8
        and inspection.prop_count == 10
        and inspection.props_with_sound == 10
        and inspection.unique_prop_sound_count >= 8
        and inspection.setpiece_actor_count >= 90
        and inspection.mechanism_actor_count >= 120
        and inspection.dressing_actor_count >= 150
        and inspection.camera_actor_count == 5
        and inspection.path_actor_count >= 50
        and inspection.playability_actor_count >= 150
        and inspection.playability_room_count == 5
        and inspection.playability_reach_target_count >= 15
        and inspection.playability_door_clearance_count >= 20
        and inspection.hint_actor_count >= 100
        and inspection.hint_room_count == 5
        and inspection.hint_penalty_step_count == 15
        and inspection.hint_staff_channel_count >= 15
        and inspection.timer_actor_count >= 80
        and inspection.timer_room_count == 5
        and inspection.timer_countdown_display_count == 5
        and inspection.timer_emergency_channel_count >= 15
        and inspection.spatial_audio_actor_count >= 60
        and inspection.first_person_foley_actor_count >= 180
        and inspection.first_person_foley_room_count == 5
        and inspection.first_person_foley_emitter_count >= 25
        and inspection.unique_foley_sound_count >= 14
        and inspection.door_transition_actor_count >= 90
        and inspection.door_transition_pair_count == 4
        and inspection.door_transition_emitter_count >= 4
        and inspection.door_hardware_actor_count >= 250
        and inspection.door_hardware_door_count == 5
        and inspection.door_hardware_hinge_pin_count == 15
        and inspection.door_hardware_handle_count == 5
        and inspection.door_hardware_closer_count == 5
        and inspection.door_hardware_seal_count >= 20
        and inspection.door_hardware_strike_count == 5
        and inspection.door_hardware_tactile_count >= 15
        and inspection.door_hardware_audio_anchor_count == 5
        and inspection.door_hardware_sensor_count >= 15
        and inspection.operations_actor_count >= 300
        and inspection.operations_room_count == 5
        and inspection.operations_intercom_count == 5
        and inspection.operations_emergency_release_count == 5
        and inspection.operations_reset_checklist_count == 5
        and inspection.operations_cctv_recording_count == 5
        and inspection.operations_no_force_label_count == 15
        and inspection.operations_maglock_status_count == 5
        and inspection.operations_staff_key_count == 5
        and inspection.operations_maintenance_count >= 80
        and inspection.operations_prop_inventory_count == 5
        and inspection.operations_audio_anchor_count == 5
        and inspection.lighting_quality_actor_count >= 140
        and inspection.lighting_quality_room_count == 5
        and inspection.lighting_quality_post_process_count == 5
        and inspection.lighting_quality_key_light_count == 5
        and inspection.lighting_quality_fill_light_count == 5
        and inspection.lighting_quality_rim_light_count == 5
        and inspection.lighting_quality_puzzle_light_count == 5
        and inspection.lighting_quality_exit_light_count == 5
        and inspection.lighting_quality_volumetric_beam_count >= 20
        and inspection.lighting_quality_dust_mote_count >= 40
        and inspection.lighting_quality_reflection_card_count >= 15
        and inspection.lighting_quality_shadow_catcher_count >= 15
        and inspection.lighting_quality_exposure_anchor_count == 5
        and inspection.puzzle_feedback_actor_count >= 180
        and inspection.puzzle_feedback_room_count == 5
        and inspection.puzzle_feedback_station_count == 10
        and inspection.puzzle_feedback_success_lamp_count == 10
        and inspection.puzzle_feedback_error_lamp_count == 10
        and inspection.puzzle_feedback_progress_node_count >= 45
        and inspection.puzzle_feedback_correction_frame_count == 30
        and inspection.puzzle_feedback_reward_glow_count == 10
        and inspection.puzzle_feedback_reset_cue_count == 10
        and inspection.puzzle_feedback_hand_rebound_count == 10
        and inspection.puzzle_feedback_audio_anchor_count == 30
        and inspection.clue_chain_actor_count >= 90
        and inspection.cross_room_chain_actor_count >= 50
        and inspection.cross_room_fragment_count == 4
        and inspection.cross_room_receiver_slot_count >= 4
        and inspection.cross_room_dependency_line_count >= 8
        and inspection.progress_actor_count >= 50
        and inspection.lock_motion_actor_count >= 150
        and inspection.lock_operation_actor_count >= 200
        and inspection.lock_operation_station_count == 10
        and inspection.unique_lock_operation_kind_count == 8
        and inspection.lock_hardware_actor_count >= 190
        and inspection.lock_hardware_station_count == 10
        and inspection.lock_hardware_room_count == 5
        and inspection.lock_hardware_shackle_count == 10
        and inspection.lock_hardware_keyway_count == 10
        and inspection.lock_hardware_tactile_count == 10
        and inspection.lock_hardware_sound_port_count == 10
        and inspection.lock_hardware_feedback_lamp_count == 20
        and inspection.lock_hardware_detail_count >= 50
        and inspection.lock_hardware_unique_kind_count == 8
        and inspection.search_surface_actor_count >= 240
        and inspection.escape_cafe_prop_actor_count >= 300
        and inspection.escape_cafe_prop_room_count == 5
        and inspection.escape_cafe_prop_station_count == 30
        and inspection.escape_cafe_prop_hidden_panel_count >= 18
        and inspection.escape_cafe_prop_key_cache_count >= 15
        and inspection.escape_cafe_prop_lock_hardware_count >= 12
        and inspection.escape_cafe_prop_direction_route_count >= 15
        and inspection.escape_cafe_prop_electronic_input_count >= 25
        and inspection.escape_cafe_prop_reveal_ghost_count == 30
        and inspection.escape_cafe_prop_tactile_target_count == 30
        and inspection.escape_cafe_prop_audio_anchor_count == 30
        and inspection.secret_discovery_actor_count >= 200
        and inspection.secret_discovery_room_count == 5
        and inspection.secret_discovery_hidden_panel_count == 15
        and inspection.secret_discovery_reveal_ghost_count >= 15
        and inspection.secret_discovery_reward_cache_count == 15
        and inspection.secret_discovery_tool_cue_count == 15
        and inspection.secret_discovery_dependency_link_count == 15
        and inspection.runtime_secret_actor_count >= 60
        and inspection.runtime_secret_room_count == 5
        and inspection.runtime_secret_interactable_count == 15
        and inspection.runtime_secret_sound_count == 15
        and inspection.runtime_secret_reward_key_count == 15
        and inspection.runtime_secret_required_key_count >= 14
        and inspection.runtime_secret_motion_count == 15
        and inspection.ending_actor_count >= 65
        and inspection.ending_photo_spot_count >= 5
        and inspection.ending_letter_count >= 3
        and inspection.ending_audio_cue_count >= 10
        and inspection.room_shape_actor_count >= 30
        and inspection.room_shape_room_count == 5
        and inspection.unique_room_footprint_count == 5
        and inspection.cinematic_actor_count >= 60
        and inspection.cinematic_room_count == 5
        and inspection.visual_actor_count >= 45
        and inspection.material_asset_count >= 10
        and inspection.audio_asset_count >= 36
        and inspection.hud_class_loaded
        and inspection.runtime_escape_cafe_prop_actor_count >= 90
        and inspection.runtime_escape_cafe_prop_room_count == 5
        and inspection.runtime_escape_cafe_prop_interactable_count == 30
        and inspection.runtime_escape_cafe_prop_sound_count == 30
        and inspection.runtime_escape_cafe_prop_reward_key_count == 30
        and inspection.runtime_escape_cafe_prop_motion_count == 30
        and inspection.runtime_escape_cafe_prop_hardware_count == 30
        and inspection.runtime_escape_cafe_prop_cue_count == 30
        and inspection.runtime_escape_cafe_prop_glow_count == 30
        and inspection.room_dressing_quality_actor_count >= 190
        and inspection.room_dressing_quality_room_count == 5
        and inspection.room_dressing_quality_wall_panel_count == 25
        and inspection.room_dressing_quality_trim_count == 15
        and inspection.room_dressing_quality_ceiling_service_count == 25
        and inspection.room_dressing_quality_practical_light_count == 5
        and inspection.room_dressing_quality_search_affordance_count == 30
        and inspection.room_dressing_quality_wear_count >= 40
        and inspection.room_dressing_quality_material_break_count == 30
    )
